@startuml
'https://plantuml.com/activity-diagram-beta

start
#LightSeaGreen:Customer Who has purchased a property in stallments;
#LightSeaGreen:Mobile app;
#LightSeaGreen:Login Page;
#LightSeaGreen:Specify credentials;
#LightSeaGreen:Click Login Button;
#LightSeaGreen:HomePage;
#LightSeaGreen:Portfolio;

@enduml
